require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config.ru'
    - 'app/helpers/**/*'
    - 'app/controllers/application_controller.rb'
    - 'spec/factories.rb'
    - 'node_modules/**/*'
    - 'app/models/user.rb'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'it']

StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false
