development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:4ac3910c9da085cb62298bc906ca84b2@scat.redistogo.com:9278/
  channel_prefix: chess_production
