development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://:pc5e2bbbfc090e04c394fcd703209adf0af148f59812b86d5e2efc4c96e30886c@ec2-52-2-3-26.compute-1.amazonaws.com:28719
  channel_prefix: chess_production
