development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://:pc5e2bbbfc090e04c394fcd703209adf0af148f59812b86d5e2efc4c96e30886c@ec2-107-20-220-72.compute-1.amazonaws.com:12999
  channel_prefix: chess_production
